# Content edited based on https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme
# Following "Remote Theme Method"
source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-include-cache", group: jekyll_plugins
